// Generated by `wit-bindgen-wrpc-go` 0.8.0. DO NOT EDIT!
// server package contains wRPC bindings for `server` world
package server

import (
	exports__lxfontes__unprovider__runner "github.com/lxfontes/unprovider/internal/server/exports/lxfontes/unprovider/runner"
	wrpc "wrpc.io/go"
)

func Serve(s wrpc.Server, h0 exports__lxfontes__unprovider__runner.Handler) (stop func() error, err error) {
	stops := make([]func() error, 0, 1)
	stop = func() error {
		for _, stop := range stops {
			if err := stop(); err != nil {
				return err
			}
		}
		return nil
	}
	stop0, err := exports__lxfontes__unprovider__runner.ServeInterface(s, h0)
	if err != nil {
		return
	}
	stops = append(stops, stop0)
	stop = func() error {
		if err := stop0(); err != nil {
			return err
		}
		return nil
	}
	return
}
